# Generated by Django 4.2 on 2023-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="categories",
            field=models.ManyToManyField(null=True, to="blog.category"),
        ),
    ]
